1. Initialize an empty array with size 2X2.


In [ ]:
import numpy as np
arr= np.random.randint(0,1,(2,2))
print(arr)

[[0 0]
 [0 0]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
import random
arr= np.random.randint(1,2,(4,2))
print(arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
filled_array = np.full((3, 3),fill_value= 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}


In [ ]:
import numpy as np
zeros_like=np.zeros_like(filled_array)
print(zeros_like)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
ones_like = np.ones_like(filled_array)
print(ones_like)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


Problem - 2:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np
array_10_to_49 = np.arange(10, 50)
print(array_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np
array_0_8= np.reshape((np.arange(0,9)),(3,3))
print(array_0_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
random_array = np.random.rand(30)
mean_arr = random_array.mean()
print(mean_arr)

0.5219407939567698
0.5560372593009751
0.524291858897438


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
array = np.random.randint(1,100,size=(10,10))
min_val = array.min()
max_val = array.max()
print("The random elements array is: ",array)
print("The min value of the matrix is:",min_val)
print("The max value of the matrix is:",max_val)

The random elements array is:  [[ 3 76  4 37 66 11 85  4 84 34]
 [89 83  8 99  4 44 48 48 40 58]
 [54 44 70  5 55 84 64 28 57 26]
 [64 95 51  2 97  2 68 24 23 91]
 [20 28 84 67 79 69 77 40 65 16]
 [78  8 32 78 16 84 93 17 93 96]
 [72  9  3 74 91 82 59 41 52 72]
 [10 43 17 94 93  8 15 69 24 36]
 [68 98 67 89 56 49 19 56 33 73]
 [66 38  5 41 85 11 65 34 66 44]]
The min value of the matrix is: 2
The max value of the matrix is: 99


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np
array = np.zeros((10,10))
print(array)
array[0][4]= 1
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np
array = [1,2,0,0,4,0]
array.reverse()
# array.sort()
print(array)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0,:]=1
array[-1,:] =1
array[:,0]=1
array[:,-1]=1
print(array)

[[1 1 1]
 [1 5 1]
 [1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
check = np.random.randint(0,1,(8,8))
check[1::2, ::2] = 1
check[::2, 1::2] = 1
print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3:
1. Add the two array.


In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result1 = x+y
result2 = np.add(x,y)
print(result1)
print(result2)

v = np.array([9,10])
w = np.array([11,12])
result1 = np.add(v,w)
print(result1)

[[ 6  8]
 [10 13]]
[[ 6  8]
 [10 13]]
[20 22]


2. Subtract the two array.


In [ ]:
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result = np.subtract(x,y)
print(result)

v = np.array([9,10])
w = np.array([11,12])
result = np.subtract(v,w)
print(result)

[[-4 -4]
 [-4 -3]]
[-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

res1 = v*2
res2= w*3
res3 = x*4
res4=y*5

print(res1)
print(res2)
print(res3)
print(res4)

[18 20]
[33 36]
[[ 4  8]
 [12 20]]
[[25 30]
 [35 40]]


4. Find the square of each element of the array.


In [ ]:
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

square1 = np.square(v)
square2 = np.square(w)
square3 = np.square(x)
square4 = np.square(y)
print(square1,"\n", square2,"\n", square3,"\n", square4)

[ 81 100] 
 [121 144] 
 [[ 1  4]
 [ 9 25]] 
 [[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [ ]:
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

result1 = np.dot(v,w)
result2 = np.dot(x,v)
result3 =np.dot(x,y)

print(result1)
print(result2)
print(result3)

219
[29 77]
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.


In [ ]:
# Part 3
# Ques 6
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result1 = np.concatenate((v,w))
result2 = np.concatenate((x,y),axis = 1)
print(result1)
print(result2)
result3 = np.concatenate((x,v))
print(result3)
# dimensional error

[ 9 10 11 12]
[[1 2 5 6]
 [3 5 7 8]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result3 = np.concatenate((x,v))
print(result3)
# dimensional error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4:
Question 1


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv=np.linalg.inv(A)
result = np.dot(A_inv,A)
result = np.round(result, decimals=10)
I = np.eye(2,2)
# print(I)
if np.allclose(result,I) :
    print("Equal")
else:
    print("Not equal")

Equal


Question 2:

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
res1 = np.matmul(A,B)
res2 = np.matmul(B,A)
if np.allclose(res1,res2):
    print("Equal")
else:
    print("Not equal")

Not equal


Question 3:


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
res1 = np.matmul(A,B)
transpAB = np.transpose(res1)
transpA = np.transpose(A)
transpB = np.transpose(B)
res2 = np.matmul(transpB,transpA)
if np.allclose(transpAB,res2):
        print("Equal")
else:
        print("Not equal")

Equal


Question 4 :

In [ ]:
import numpy as np
A= ([[2,-3,1],
    [1,-1,2],
    [3,1,-1]])

B= ([-1],
    [-3],
    [9])

A_inv = np.linalg.inv(A)
res = np.dot(A_inv,B)
print("The solution is: ")
print(res)

The solution is: 
[[ 2.]
 [ 1.]
 [-2.]]
